name = "markdown"
description = "Markdown parser"
version = "0.1.0-dev"
tags = ["markdown", "gfm", "commonmark"]

authors = ["AdaCore"]
maintainers = ["Max Reznik <reznik@adacore.com>"]
maintainers-logins = ["reznikmm"]
licenses = "Apache-2.0"

project-files = ["gnat/markdown.gpr"]

[configuration]
disabled = true

[[depends-on]]
vss = "^22.0.0"

[origin]
url = "https://github.com/AdaCore/markdown.git"
commit = "82fc97b0a5d5ec370f95c041bd53b5c2bcfc2e9c"