description = "Open Database Connectivity drivers for UNIX platforms"
website = "http://www.unixodbc.org"
name = "unixodbc"

maintainers = ["alejandro@mosteo.com"]
maintainers-logins = ["mosteo"]

[[external]]
kind = "system"

[external.origin."case(distribution)"]
"..." = []
"debian|ubuntu" = ["unixodbc-dev"]
"msys2" = ["mingw-w64-x86_64-unixodbc"]
"fedora" = ["unixODBC-devel"]

[[external]]
kind = "version-output"
version-command = [ "odbc_config", "--version" ]
version-regexp = "([\\d\\.]+)"
